dist: bionic
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- pytest
before_install:
- openssl aes-256-cbc -md sha512 -camellia-128-cfb -iter 1000 -nosalt -d -in .travis/skey.enc -out ./id_rsa -k $SHA_KEY
- ssh-agent /bin/sh | ssh-add id_rsa


- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- ssh -i ./deploy_key $	USR@$IP $PWD
