dist: bionic
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- pytest
script:
- openssl aes-256-cbc -md sha512 -camellia-256-ecb -iter 1000 -nosalt -in .travis/skey.enc -d -out ./deploy_key -k $SHA_KEY
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key

after success:
- ./.script.sh
